"use client";

import { useActionState, useState } from "react";
import { verifyMfaAction, type MfaVerifyState } from "@/actions/auth";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input, Label } from "@/components/ui/input";
import { AlertCircle } from "lucide-react";

const initialState: MfaVerifyState = { success: false };

export function MfaChallengeForm() {
  const [state, formAction, pending] = useActionState(verifyMfaAction, initialState);
  const [useRecovery, setUseRecovery] = useState(false);

  return (
    <div className="w-full max-w-md mx-auto p-8">
      <div className="bg-white border border-brand-charcoal/10 p-10">
        <div className="text-center mb-8">
          <Image
            src="/images/SSIS.webp"
            alt="Seven Seas Intercontinental"
            width={64}
            height={64}
            className="mx-auto mb-4"
          />
          <h1 className="text-xl font-semibold text-brand-black">
            Two-Factor Authentication
          </h1>
          <p className="text-sm text-brand-muted mt-1">
            {useRecovery 
              ? "Enter one of your recovery codes." 
              : "Enter the code generated by your authenticator app."}
          </p>
        </div>

        {state.message && !state.success && (
          <div className="flex items-center gap-2 p-3 mb-6 bg-red-50 text-sm text-red-700 border border-red-100">
            <AlertCircle className="w-4 h-4 flex-shrink-0" />
            {state.message}
          </div>
        )}

        <form action={formAction} className="space-y-5">
          <input type="hidden" name="isRecovery" value={useRecovery ? "true" : "false"} />
          <div>
            <Label htmlFor="code" required>
              {useRecovery ? "Recovery Code" : "Authentication Code"}
            </Label>
            <Input
              id="code"
              name="code"
              type="text"
              required
              autoComplete="off"
              autoFocus
              placeholder={useRecovery ? "e.g. abcd-1234" : "123456"}
              error={state.errors?.code?.[0]}
            />
          </div>
          <Button
            type="submit"
            variant="primary"
            size="lg"
            fullWidth
            disabled={pending}
          >
            {pending ? "Verifying..." : "Verify"}
          </Button>
        </form>
        
        <div className="mt-6 text-center">
          <button 
            type="button" 
            onClick={() => setUseRecovery(!useRecovery)}
            className="text-sm text-brand-gold hover:underline"
          >
            {useRecovery ? "Use Authenticator App" : "Use Recovery Code"}
          </button>
        </div>
      </div>
      <p className="text-center text-xs text-brand-muted mt-4">
        © {new Date().getFullYear()} Seven Seas Intercontinental
      </p>
    </div>
  );
}
