// ============================================================
// Demo Demands Data — Illustrative Only
// ============================================================
// All company names, reference numbers, and vacancy details
// are fictional and for demonstration purposes only.
// ============================================================

import type { CmsDemand } from "@/types/content";

export const demoDemands: CmsDemand[] = [
  // ── Demand 1: Security (Dubai) — OPEN ──────────────────
  {
    id: "demand-1",
    slug: "security-guards-supervisors-dubai-2026",
    title: "Security Guards & Supervisors — Dubai",
    companyName: "Demo Gulf Security Corp",
    industry: "Security Services",
    industrySlug: "security-services",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Dubai",
    demandReferenceNumber: "DEMO-SS-2026-001",
    approvalDate: "2026-06-15T00:00:00Z",
    receivedDate: "2026-06-10T00:00:00Z",
    applicationStartDate: "2026-07-01T00:00:00Z",
    applicationDeadline: "2026-08-30T00:00:00Z",
    interviewDate: "2026-08-10T00:00:00Z",
    interviewLocation: "Seven Seas Office, Kathmandu",
    contractType: "2-Year Fixed Term",
    generalNotes: "DEMO / ILLUSTRATIVE ONLY — This is not a real vacancy. All details are fictional for demonstration purposes.",
    status: "PUBLISHED",
    statusBadge: "Open",
    isPublic: true,
    enableApplication: true,
    feeTransparencyNotice: "Seven Seas Intercontinental does not charge candidates any fee for job placement.",
    candidateSafetyNotice: "Do not make any payment or submit original documents unless instructed through an official Seven Seas Intercontinental communication channel.",
    totalPositions: 3,
    totalManpower: 175,
    totalVacancies: 175,
    applicationStatus: "OPEN",
    applicationStatusLabel: "Applications Open",
    canApply: true,
    positions: [
      {
        id: "pos-1-1",
        demandId: "demand-1",
        displayOrder: 1,
        title: "Security Guard",
        maleCount: 120,
        femaleCount: 0,
        totalCount: 120,
        minimumQualification: "High School Diploma (SLC/SEE)",
        requiredExperience: "1+ year security experience",
        requiredSkills: "Physical fitness, English communication",
        salaryCurrency: "AED",
        salaryAmount: "2,200",
        nprEquivalent: "~NPR 80,000",
        overtimeStatus: "YES",
        overtimeNotes: "1.25x hourly rate",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "30 days",
        foodFacilityStatus: "PROVIDED",
        foodFacilityNotes: "3 meals per day in company mess",
        accommodationStatus: "PROVIDED",
        accommodationNotes: "Shared accommodation in labour camp",
        contractPeriod: "2 Years (Renewable)",
        otherBenefits: "Medical insurance, annual flight ticket",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-1-2",
        demandId: "demand-1",
        displayOrder: 2,
        title: "Senior Security Guard",
        maleCount: 40,
        femaleCount: 0,
        totalCount: 40,
        minimumQualification: "High School Diploma + SIRA Certification",
        requiredExperience: "3+ years in GCC security",
        requiredSkills: "Access control, CCTV monitoring, incident reporting",
        salaryCurrency: "AED",
        salaryAmount: "2,800",
        nprEquivalent: "~NPR 102,000",
        overtimeStatus: "YES",
        overtimeNotes: "1.25x hourly rate",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "30 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years (Renewable)",
        otherBenefits: "Medical insurance, annual flight ticket",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-1-3",
        demandId: "demand-1",
        displayOrder: 3,
        title: "Security Supervisor",
        maleCount: 12,
        femaleCount: 3,
        totalCount: 15,
        minimumQualification: "Bachelor's Degree + SIRA Certification",
        requiredExperience: "5+ years, 2+ years supervisory",
        requiredSkills: "Team management, incident investigation, reporting",
        salaryCurrency: "AED",
        salaryAmount: "4,500",
        nprEquivalent: "~NPR 164,000",
        overtimeStatus: "NO",
        workHoursPerDay: "8",
        workDaysPerWeek: "5",
        annualLeave: "30 days",
        foodFacilityStatus: "ALLOWANCE_PROVIDED",
        foodFacilityNotes: "AED 500/month food allowance",
        accommodationStatus: "ALLOWANCE_PROVIDED",
        accommodationNotes: "AED 1,500/month housing allowance",
        contractPeriod: "2 Years (Renewable)",
        otherBenefits: "Medical insurance, annual flight ticket, gratuity",
        status: "OPEN",
        isPublic: true,
      },
    ],
    documents: [],
    publishedAt: "2026-07-01T00:00:00Z",
    createdAt: "2026-06-15T00:00:00Z",
    updatedAt: "2026-07-01T00:00:00Z",
    createdByName: "Admin",
  },

  // ── Demand 2: Construction (Qatar) — OPEN ──────────────
  {
    id: "demand-2",
    slug: "construction-workers-qatar-infrastructure-2026",
    title: "Construction Workers — Qatar Infrastructure Project",
    companyName: "Demo Al-Rashid Construction",
    industry: "Construction & Technical Trades",
    industrySlug: "construction-and-technical-trades",
    country: "Qatar",
    countryCode: "QA",
    city: "Doha",
    demandReferenceNumber: "DEMO-SS-2026-002",
    approvalDate: "2026-06-20T00:00:00Z",
    receivedDate: "2026-06-18T00:00:00Z",
    applicationStartDate: "2026-07-05T00:00:00Z",
    applicationDeadline: "2026-09-15T00:00:00Z",
    interviewDate: "2026-08-25T00:00:00Z",
    interviewLocation: "Seven Seas Office, Kathmandu",
    contractType: "2-Year Fixed Term",
    generalNotes: "DEMO / ILLUSTRATIVE ONLY — This is not a real vacancy.",
    status: "PUBLISHED",
    statusBadge: "Open",
    isPublic: true,
    enableApplication: true,
    feeTransparencyNotice: "Seven Seas Intercontinental does not charge candidates any fee for job placement.",
    candidateSafetyNotice: "Do not make any payment or submit original documents unless instructed through an official Seven Seas Intercontinental communication channel.",
    totalPositions: 4,
    totalManpower: 280,
    totalVacancies: 280,
    applicationStatus: "OPEN",
    applicationStatusLabel: "Applications Open",
    canApply: true,
    positions: [
      {
        id: "pos-2-1",
        demandId: "demand-2",
        displayOrder: 1,
        title: "Mason / Bricklayer",
        maleCount: 80,
        totalCount: 80,
        minimumQualification: "Literate / Basic Education",
        requiredExperience: "2+ years construction",
        requiredSkills: "Bricklaying, plastering, tile work",
        salaryCurrency: "QAR",
        salaryAmount: "1,800",
        nprEquivalent: "~NPR 66,000",
        overtimeStatus: "YES",
        overtimeNotes: "1.5x hourly rate",
        workHoursPerDay: "10",
        workDaysPerWeek: "6",
        annualLeave: "21 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-2-2",
        demandId: "demand-2",
        displayOrder: 2,
        title: "Steel Fixer",
        maleCount: 100,
        totalCount: 100,
        minimumQualification: "Literate / Basic Education",
        requiredExperience: "2+ years",
        requiredSkills: "Rebar cutting, bending, tying",
        salaryCurrency: "QAR",
        salaryAmount: "1,900",
        nprEquivalent: "~NPR 70,000",
        overtimeStatus: "YES",
        workHoursPerDay: "10",
        workDaysPerWeek: "6",
        annualLeave: "21 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-2-3",
        demandId: "demand-2",
        displayOrder: 3,
        title: "Heavy Equipment Operator",
        maleCount: 40,
        totalCount: 40,
        minimumQualification: "SLC/SEE + Valid Operator License",
        requiredExperience: "3+ years with excavators/loaders",
        requiredSkills: "Excavator, loader, bulldozer operation",
        salaryCurrency: "QAR",
        salaryAmount: "2,500",
        nprEquivalent: "~NPR 92,000",
        overtimeStatus: "YES",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "21 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-2-4",
        demandId: "demand-2",
        displayOrder: 4,
        title: "Site Foreman",
        maleCount: 55,
        femaleCount: 5,
        totalCount: 60,
        minimumQualification: "Diploma in Civil Engineering",
        requiredExperience: "5+ years, supervisory role",
        requiredSkills: "Team management, blueprint reading, safety protocols",
        salaryCurrency: "QAR",
        salaryAmount: "3,500",
        nprEquivalent: "~NPR 129,000",
        overtimeStatus: "NO",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "30 days",
        foodFacilityStatus: "ALLOWANCE_PROVIDED",
        foodFacilityNotes: "QAR 400/month",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        otherBenefits: "Medical, annual flight",
        status: "OPEN",
        isPublic: true,
      },
    ],
    documents: [],
    publishedAt: "2026-07-05T00:00:00Z",
    createdAt: "2026-06-20T00:00:00Z",
    updatedAt: "2026-07-05T00:00:00Z",
    createdByName: "Admin",
  },

  // ── Demand 3: Hospitality (Saudi Arabia) — CLOSING SOON ─
  {
    id: "demand-3",
    slug: "hospitality-staff-riyadh-2026",
    title: "Hospitality & Hotel Staff — Riyadh",
    companyName: "Demo Royal Hospitality Group",
    industry: "Hospitality & Hotels",
    industrySlug: "hospitality-and-hotels",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    demandReferenceNumber: "DEMO-SS-2026-003",
    approvalDate: "2026-05-20T00:00:00Z",
    applicationStartDate: "2026-06-01T00:00:00Z",
    applicationDeadline: "2026-07-12T00:00:00Z",
    interviewDate: "2026-07-20T00:00:00Z",
    interviewLocation: "Seven Seas Office, Kathmandu",
    contractType: "2-Year Fixed Term",
    generalNotes: "DEMO / ILLUSTRATIVE ONLY — This is not a real vacancy.",
    status: "PUBLISHED",
    statusBadge: "Closing Soon",
    isPublic: true,
    enableApplication: true,
    feeTransparencyNotice: "Seven Seas Intercontinental does not charge candidates any fee for job placement.",
    candidateSafetyNotice: "Do not make any payment or submit original documents unless instructed through an official Seven Seas Intercontinental communication channel.",
    totalPositions: 5,
    totalManpower: 85,
    totalVacancies: 85,
    applicationStatus: "OPEN",
    applicationStatusLabel: "Applications Open",
    canApply: true,
    positions: [
      {
        id: "pos-3-1",
        demandId: "demand-3",
        displayOrder: 1,
        title: "Waiter / Waitress",
        maleCount: 20,
        femaleCount: 10,
        totalCount: 30,
        minimumQualification: "SLC/SEE",
        requiredExperience: "1+ year in F&B",
        requiredSkills: "Customer service, English",
        salaryCurrency: "SAR",
        salaryAmount: "2,000",
        nprEquivalent: "~NPR 71,000",
        overtimeStatus: "YES",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "21 days",
        foodFacilityStatus: "PROVIDED",
        foodFacilityNotes: "Duty meals",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-3-2",
        demandId: "demand-3",
        displayOrder: 2,
        title: "Room Attendant",
        maleCount: 10,
        femaleCount: 15,
        totalCount: 25,
        minimumQualification: "SLC/SEE",
        requiredExperience: "6 months housekeeping",
        salaryCurrency: "SAR",
        salaryAmount: "1,800",
        nprEquivalent: "~NPR 64,000",
        overtimeStatus: "YES",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "21 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-3-3",
        demandId: "demand-3",
        displayOrder: 3,
        title: "Cook / Chef de Partie",
        maleCount: 10,
        totalCount: 10,
        minimumQualification: "Culinary diploma",
        requiredExperience: "3+ years hotel kitchen",
        requiredSkills: "International cuisine, HACCP",
        salaryCurrency: "SAR",
        salaryAmount: "2,800",
        nprEquivalent: "~NPR 100,000",
        overtimeStatus: "NOT_SPECIFIED",
        workHoursPerDay: "9",
        workDaysPerWeek: "6",
        annualLeave: "21 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-3-4",
        demandId: "demand-3",
        displayOrder: 4,
        title: "Front Desk Receptionist",
        maleCount: 5,
        femaleCount: 5,
        totalCount: 10,
        minimumQualification: "Diploma in Hotel Management",
        requiredExperience: "2+ years front desk",
        requiredSkills: "Opera PMS, fluent English, customer service",
        salaryCurrency: "SAR",
        salaryAmount: "2,500",
        nprEquivalent: "~NPR 89,000",
        overtimeStatus: "NO",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "30 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        otherBenefits: "Medical insurance, annual flight",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-3-5",
        demandId: "demand-3",
        displayOrder: 5,
        title: "Housekeeping Supervisor",
        maleCount: 5,
        femaleCount: 5,
        totalCount: 10,
        minimumQualification: "Diploma + supervisory experience",
        requiredExperience: "4+ years housekeeping, 1+ supervisory",
        salaryCurrency: "SAR",
        salaryAmount: "3,200",
        nprEquivalent: "~NPR 114,000",
        overtimeStatus: "NO",
        workHoursPerDay: "8",
        workDaysPerWeek: "5",
        annualLeave: "30 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "ALLOWANCE_PROVIDED",
        accommodationNotes: "SAR 800/month housing allowance",
        contractPeriod: "2 Years",
        otherBenefits: "Medical, flight, end-of-service gratuity",
        status: "OPEN",
        isPublic: true,
      },
    ],
    documents: [],
    publishedAt: "2026-06-01T00:00:00Z",
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-06-01T00:00:00Z",
    createdByName: "Admin",
  },

  // ── Demand 4: Manufacturing (Kuwait) — UPCOMING ─────────
  {
    id: "demand-4",
    slug: "manufacturing-operators-kuwait-2026",
    title: "Manufacturing & Assembly Operators — Kuwait",
    companyName: "Demo Kuwait Industrial Co.",
    industry: "Manufacturing",
    industrySlug: "manufacturing",
    country: "Kuwait",
    countryCode: "KW",
    city: "Ahmadi",
    demandReferenceNumber: "DEMO-SS-2026-004",
    approvalDate: "2026-07-01T00:00:00Z",
    receivedDate: "2026-06-28T00:00:00Z",
    applicationStartDate: "2026-07-20T00:00:00Z",
    applicationDeadline: "2026-09-30T00:00:00Z",
    contractType: "2-Year Fixed Term",
    generalNotes: "DEMO / ILLUSTRATIVE ONLY — This is not a real vacancy.",
    status: "PUBLISHED",
    statusBadge: "Upcoming",
    isPublic: true,
    enableApplication: false,
    feeTransparencyNotice: "Seven Seas Intercontinental does not charge candidates any fee for job placement.",
    candidateSafetyNotice: "Do not make any payment or submit original documents unless instructed through an official Seven Seas Intercontinental communication channel.",
    totalPositions: 2,
    totalManpower: 60,
    totalVacancies: 60,
    applicationStatus: "NOT_YET_OPEN",
    applicationStatusLabel: "Applications Not Yet Open",
    canApply: false,
    positions: [
      {
        id: "pos-4-1",
        demandId: "demand-4",
        displayOrder: 1,
        title: "Machine Operator",
        maleCount: 35,
        femaleCount: 5,
        totalCount: 40,
        minimumQualification: "SLC/SEE + Technical Training",
        requiredExperience: "1+ year in manufacturing",
        requiredSkills: "CNC operation, quality inspection",
        salaryCurrency: "KWD",
        salaryAmount: "180",
        nprEquivalent: "~NPR 78,000",
        overtimeStatus: "YES",
        overtimeNotes: "1.5x rate after 8 hours",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "30 days",
        foodFacilityStatus: "NOT_PROVIDED",
        foodFacilityNotes: "KWD 25/month food allowance",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "OPEN",
        isPublic: true,
      },
      {
        id: "pos-4-2",
        demandId: "demand-4",
        displayOrder: 2,
        title: "Quality Control Inspector",
        maleCount: 15,
        femaleCount: 5,
        totalCount: 20,
        minimumQualification: "Diploma in Mechanical/Industrial Engineering",
        requiredExperience: "2+ years QC in manufacturing",
        requiredSkills: "Measurement tools, ISO standards, reporting",
        salaryCurrency: "KWD",
        salaryAmount: "250",
        nprEquivalent: "~NPR 109,000",
        overtimeStatus: "NO",
        workHoursPerDay: "8",
        workDaysPerWeek: "5",
        annualLeave: "30 days",
        foodFacilityStatus: "ALLOWANCE_PROVIDED",
        foodFacilityNotes: "KWD 30/month",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        otherBenefits: "Medical insurance, annual flight",
        status: "OPEN",
        isPublic: true,
      },
    ],
    documents: [],
    createdAt: "2026-07-01T00:00:00Z",
    updatedAt: "2026-07-01T00:00:00Z",
    createdByName: "Admin",
  },

  // ── Demand 5: Healthcare Support (Oman) — CLOSED ────────
  {
    id: "demand-5",
    slug: "healthcare-support-staff-muscat-2026",
    title: "Healthcare Support Staff — Muscat",
    companyName: "Demo Oman Medical Services",
    industry: "Healthcare",
    industrySlug: "healthcare",
    country: "Oman",
    countryCode: "OM",
    city: "Muscat",
    demandReferenceNumber: "DEMO-SS-2026-005",
    approvalDate: "2026-04-10T00:00:00Z",
    receivedDate: "2026-04-05T00:00:00Z",
    applicationStartDate: "2026-04-20T00:00:00Z",
    applicationDeadline: "2026-06-15T00:00:00Z",
    interviewDate: "2026-05-20T00:00:00Z",
    interviewLocation: "Seven Seas Office, Kathmandu",
    contractType: "2-Year Fixed Term",
    generalNotes: "DEMO / ILLUSTRATIVE ONLY — This is not a real vacancy. This demand has been closed.",
    status: "CLOSED",
    statusBadge: "Closed",
    isPublic: true,
    enableApplication: false,
    feeTransparencyNotice: "Seven Seas Intercontinental does not charge candidates any fee for job placement.",
    candidateSafetyNotice: "Do not make any payment or submit original documents unless instructed through an official Seven Seas Intercontinental communication channel.",
    totalPositions: 3,
    totalManpower: 45,
    totalVacancies: 45,
    applicationStatus: "CLOSED",
    applicationStatusLabel: "Applications Closed",
    canApply: false,
    positions: [
      {
        id: "pos-5-1",
        demandId: "demand-5",
        displayOrder: 1,
        title: "Ward Assistant / Patient Care Aide",
        maleCount: 10,
        femaleCount: 15,
        totalCount: 25,
        minimumQualification: "SLC/SEE + Basic Health Training",
        requiredExperience: "6 months healthcare setting",
        requiredSkills: "Patient handling, hygiene protocols",
        salaryCurrency: "OMR",
        salaryAmount: "150",
        nprEquivalent: "~NPR 52,000",
        overtimeStatus: "YES",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "30 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "CLOSED",
        isPublic: true,
      },
      {
        id: "pos-5-2",
        demandId: "demand-5",
        displayOrder: 2,
        title: "Medical Lab Technician",
        maleCount: 5,
        femaleCount: 5,
        totalCount: 10,
        minimumQualification: "Diploma in Medical Lab Technology",
        requiredExperience: "2+ years lab experience",
        requiredSkills: "Blood sample collection, equipment operation",
        salaryCurrency: "OMR",
        salaryAmount: "250",
        nprEquivalent: "~NPR 87,000",
        overtimeStatus: "NO",
        workHoursPerDay: "8",
        workDaysPerWeek: "5",
        annualLeave: "30 days",
        foodFacilityStatus: "ALLOWANCE_PROVIDED",
        foodFacilityNotes: "OMR 30/month food allowance",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        otherBenefits: "Medical insurance, annual flight",
        status: "CLOSED",
        isPublic: true,
      },
      {
        id: "pos-5-3",
        demandId: "demand-5",
        displayOrder: 3,
        title: "Hospital Housekeeper",
        maleCount: 5,
        femaleCount: 5,
        totalCount: 10,
        minimumQualification: "Basic literacy",
        requiredExperience: "Not required",
        requiredSkills: "Cleaning, infection control awareness",
        salaryCurrency: "OMR",
        salaryAmount: "130",
        nprEquivalent: "~NPR 45,000",
        overtimeStatus: "YES",
        workHoursPerDay: "8",
        workDaysPerWeek: "6",
        annualLeave: "21 days",
        foodFacilityStatus: "PROVIDED",
        accommodationStatus: "PROVIDED",
        contractPeriod: "2 Years",
        status: "CLOSED",
        isPublic: true,
      },
    ],
    documents: [],
    publishedAt: "2026-04-20T00:00:00Z",
    closedAt: "2026-06-15T00:00:00Z",
    createdAt: "2026-04-10T00:00:00Z",
    updatedAt: "2026-06-15T00:00:00Z",
    createdByName: "Admin",
  },
];
