// ============================================================
// Demo Jobs Data
// ============================================================

import type { CmsJob } from "@/types/content";

export const demoJobs: CmsJob[] = [
  {
    id: "job-1",
    title: "Heavy Equipment Operator",
    slug: "heavy-equipment-operator-doha",
    description: "Seeking experienced heavy equipment operators for a large infrastructure project in Doha. Must have valid GCC experience.",
    requirements: "Minimum 5 years experience operating excavators, bulldozers, and loaders. GCC license is mandatory.",
    benefits: "Free accommodation, transportation, medical insurance, and overtime pay.",
    responsibilities: "Safely operate heavy equipment on construction sites. Perform daily maintenance checks.",
    country: "Qatar",
    countryCode: "QA",
    industry: "Construction & Technical Trades",
    employerName: "Al-Badi Construction",
    showEmployerName: true,
    salary: "QAR 2,500 - 3,500",
    showSalary: true,
    contractPeriod: "2 Years",
    employmentType: "FULL_TIME",
    experienceRequired: "5+ Years",
    skillsRequired: "Excavator, Bulldozer, Loader operation",
    educationRequired: "High School Equivalent",
    languageRequired: "Basic English or Arabic",
    status: "PUBLISHED",
    isFeatured: true,
    vacancies: 40,
    publishedAt: "2026-07-01T00:00:00Z",
    createdAt: "2026-06-15T00:00:00Z",
  },
  {
    id: "job-2",
    title: "Security Guard",
    slug: "security-guard-dubai",
    description: "Hiring security guards for high-end residential and commercial properties in Dubai.",
    requirements: "Minimum height 5'7\". Good English communication skills. Previous security or military/police background preferred. DPS/SIRA certification is a plus.",
    benefits: "Accommodation, transport, duty meals, medical insurance.",
    responsibilities: "Access control, patrolling, incident reporting, ensuring safety of premises.",
    country: "United Arab Emirates",
    countryCode: "AE",
    industry: "Security Services",
    employerName: "Falcon Security Solutions",
    showEmployerName: false,
    salary: "AED 2,260",
    showSalary: true,
    contractPeriod: "2 Years",
    employmentType: "FULL_TIME",
    experienceRequired: "1-2 Years",
    skillsRequired: "Vigilance, Communication, Physical Fitness",
    educationRequired: "High School Diploma",
    languageRequired: "English (Fluent)",
    status: "PUBLISHED",
    isFeatured: true,
    vacancies: 150,
    publishedAt: "2026-07-02T00:00:00Z",
    createdAt: "2026-06-20T00:00:00Z",
  },
  {
    id: "job-3",
    title: "Hospitality Supervisor",
    slug: "hospitality-supervisor-kuwait",
    description: "Looking for a seasoned hospitality supervisor to oversee food and beverage operations in a luxury hotel.",
    requirements: "Diploma or Degree in Hotel Management. 3+ years of supervisory experience in 4/5-star hotels.",
    benefits: "Single accommodation, duty meals, medical, annual flight ticket.",
    responsibilities: "Manage staff, ensure high-quality service, handle guest complaints, oversee daily operations.",
    country: "Kuwait",
    countryCode: "KW",
    industry: "Hospitality & Hotels",
    employerName: "Grand Plaza Hotel",
    showEmployerName: true,
    salary: "KWD 250 - 350",
    showSalary: true,
    contractPeriod: "2 Years",
    employmentType: "FULL_TIME",
    experienceRequired: "3+ Years",
    educationRequired: "Diploma/Degree in Hospitality",
    languageRequired: "English (Fluent)",
    status: "PUBLISHED",
    isFeatured: false,
    vacancies: 5,
    publishedAt: "2026-07-03T00:00:00Z",
    createdAt: "2026-06-25T00:00:00Z",
  }
];
