// ============================================================
// Demo Team Data — Seven Seas Intercontinental Leadership & Team
// ============================================================

import type { CmsTeamMember } from "@/types/content";

export const demoTeam: CmsTeamMember[] = [
  {
    id: "team-devendra-bajgai",
    name: "Devendra Bajgai",
    designation: "Executive Chairman",
    department: "Executive Board",
    bio: "Over 25 years of leadership in international recruitment, workforce planning and responsible manpower deployment across international markets. As Executive Chairman of Seven Seas Intercontinental, Devendra Bajgai steers global governance, strategic bilateral partnerships, and our zero-tolerance commitment to ethical recruitment across all source and destination corridors.",
    photo: {
      id: "media-devendra-bajgai",
      source: "LOCAL_DEMO",
      localPath: "https://res.cloudinary.com/o99xd4mq/image/upload/v1784870523/staging/seven-seas-cms/vba6r5fwrjbzttipua5e.webp",
      secureUrl: "https://res.cloudinary.com/o99xd4mq/image/upload/v1784870523/staging/seven-seas-cms/vba6r5fwrjbzttipua5e.webp",
      resourceType: "image",
      fileName: "devendra_bajgai.webp",
      altText: "Devendra Bajgai — Executive Chairman",
      mediaStatus: "REAL_APPROVED",
      visibility: "PUBLIC",
      width: 1122,
      height: 1402,
      createdAt: "2026-07-24T05:21:39.843Z",
    },
    photoAltText: "Devendra Bajgai — Executive Chairman",
    group: "LEADERSHIP",
    order: 1,
    isPublished: true,
  },
  {
    id: "team-rajendra-kc",
    name: "Rajendra KC",
    designation: "Executive Director",
    department: "Executive Directorate",
    bio: "International recruitment strategist experienced in cross-border workforce mobilisation, operational governance and ethical recruitment practices. Mr. Rajendra KC serves as the Executive Director of Seven Seas Intercontinental, providing strategic leadership and overseeing the company’s overall operations. With a strong commitment to ethical recruitment, transparency, and service excellence, Rajendra KC works to build trusted partnerships and create responsible employment opportunities for workers and international employers.",
    photo: {
      id: "media-rajendra-kc",
      source: "LOCAL_DEMO",
      localPath: "https://res.cloudinary.com/o99xd4mq/image/upload/v1784870080/staging/seven-seas-cms/vdbv1ddnbrb7qjgnegmb.webp",
      secureUrl: "https://res.cloudinary.com/o99xd4mq/image/upload/v1784870080/staging/seven-seas-cms/vdbv1ddnbrb7qjgnegmb.webp",
      resourceType: "image",
      fileName: "rajendra_kc.webp",
      altText: "Rajendra KC — Executive Director",
      mediaStatus: "REAL_APPROVED",
      visibility: "PUBLIC",
      width: 1122,
      height: 1402,
      createdAt: "2026-07-24T05:14:46.052Z",
    },
    photoAltText: "Rajendra KC — Executive Director",
    group: "LEADERSHIP",
    order: 2,
    isPublished: true,
  },
  {
    id: "team-biplav-bajgai",
    name: "Biplav Bajgai",
    designation: "Managing Director",
    department: "Executive Management",
    bio: "Leads recruitment strategy, organisational growth and international workforce partnerships with a focus on responsible recruitment. Mr. Biplav Bajgai serves as the Managing Director of Seven Seas Intercontinental, leading the company’s strategic growth and daily operations. He is committed to ethical recruitment, transparent business practices, and building trusted partnerships with international employers while creating responsible employment opportunities for workers.",
    photo: {
      id: "media-biplav-bajgai",
      source: "LOCAL_DEMO",
      localPath: "https://res.cloudinary.com/o99xd4mq/image/upload/v1784870496/staging/seven-seas-cms/mvvkr9tt6q36ddpwn5td.webp",
      secureUrl: "https://res.cloudinary.com/o99xd4mq/image/upload/v1784870496/staging/seven-seas-cms/mvvkr9tt6q36ddpwn5td.webp",
      resourceType: "image",
      fileName: "biplav_bajgai.webp",
      altText: "Biplav Bajgai — Managing Director",
      mediaStatus: "REAL_APPROVED",
      visibility: "PUBLIC",
      width: 1122,
      height: 1402,
      createdAt: "2026-07-24T05:21:39.843Z",
    },
    photoAltText: "Biplav Bajgai — Managing Director",
    linkedIn: "https://www.linkedin.com/in/biplav-bajgai-331323126/",
    group: "LEADERSHIP",
    order: 3,
    isPublished: true,
  },
  {
    id: "team-sita-sharma",
    name: "Sita Sharma",
    designation: "Operations Director",
    department: "Operations",
    bio: "Leads the sourcing, screening, and deployment teams with a focus on efficiency, compliance, and candidate support.",
    group: "PEOPLE",
    order: 4,
    isPublished: true,
  }
];
